### ISSUE TITLE
Error with input file

### ISSUE THREAD

**Issue by jjp55** [snizam001/cutfrequency#2]
Hello, 

When using your code, I keep getting the following error message

In fread(paste(bam1, ".input", sep = "")) :
  File 'IP-8hr.input' has size 0. Returning a NULL data.table.
Error in `[.data.frame`(d, , 4) : undefined columns selected
Calls: [ -> [.data.frame -> [ -> [.data.frame
Execution halted

The program looks like it is able to read in both my GFP tagged protein and my control, but this error occurs as soon as it gets to the spike-in files. Do you have any suggestions? Thank you.

**Comment by snizam001** [comment]
IP-8hr.input file has zero bytes. 
Please share: 
1. The command you used and 
2. Tree of the folder at which you were running code e.g. tree inDirectory

**Comment by jjp55** [comment]
I used the code

Rscript /Volumes/T7/cutfrequency-master/run.R -a IP-8hr -b Control-8hr -c IP-8hr-spikein -d Control-8hr -m motif.txt -x 7 -s /Volumes/T7/cutfrequency-master/ -n 20

All bam files and motif files are in /Volume/T7/ while the directory containing the codes is in cutfrequency-master which is in /Volumes/T7/

**Comment by snizam001** [comment]
There is the problem in generating IP-8hr.input file, which is bam1 means given by '-a'.  Either bedtools do not present in the path of your computer, or bam file is empty. Check if bedtools and samtools are present in your computer in the PATH.

**Comment by jjp55** [comment]
When I type in samtools and bedtools in the environment both come up with their command options. 

 I can see bedtools running and it states: 
"Unexpected file format.  Please use tab-delimited BED, GFF, or VCF. Perhaps you have non-integer starts or ends at line 1?". 

This message is received after every bam file. Am I input these files as BED files to start with?

**Comment by snizam001** [comment]
So bedtools or samtools are not a problem. Since, you are giving bam file as input to bedtools without indicating that input is bamfile, it will show error.  This error is not related to the problem you are facing.

Can you please share the head of the .bed3, .input, motif and bam files? In the case of spikeIn .input file will be empty, so you can leave it.

**Comment by jjp55** [comment]
The head for the bed3 of the samples of interest is:
1	11	144	NB501800:688:HVMYWBGXJ:2:22310:9078:3546	42	.

The input file is empty for all of the inputs (including my target). 

The motif file head is:
>ATGACGTCATMH	1-ATGACGTCATMH,	8.130818	-188.375426	0	T:94.0(27.01%),B:757.8(1.68%),P:1e-81

The bam file is:
BAM“@HD	VN:1.0	SO:coordinate
@SQ	SN:1	LN:30427671
@SQ	SN:2	LN:19698289
@SQ	SN:3	LN:23459830
@SQ	SN:4	LN:18585056
@SQ	SN:5	LN:26975502
@SQ	SN:Mt	LN:366924
@SQ	SN:Pt	LN:154478

**Comment by snizam001** [comment]
Format of motif file is wrong. Can you change it to:

chr1	13970	13981	+	8.304031	TCCTGAGTCATT
chr1	23409	23420	-	8.227320	GGTGAGTCAGTG
chr1	33101	33112	+	8.549970	GTATTAGTCATA
chr1	36799	36810	+	9.025830	GTGTGAGTCATG
chr1	42279	42290	+	7.470095	GGCTGAGTCAGG
chr1	57432	57443	-	8.303808	TGTGACTCAGAG
chr1	61274	61285	+	8.194027	CTATGAGTCAAT
chr1	65006	65017	-	8.942024	GGTGACTCACTC

You can generate this file by:

A) To generate motif file of the protein of interest proceed as follows (install homer):

	1) download file contains PWM of the motifs
		http://homer.ucsd.edu/homer/custom.motifs
	2) find protein of interest in the custom.motifs and 
	copy-paste the PWM in new file (e.g. tp53.pwm or fos.pwm)
	
	3) run following command to generate bed file containing location 
	of whole genome motifs (http://homer.ucsd.edu/homer/motif/genomeWideMotifScan.html)
	
	scanMotifGenomeWide.pl fos.pwm hg38 | cut -f2- > FOS-motifs.txt

**Comment by snizam001** [comment]
Moreover, the chromosome format in your bamfile is not chr1, chr2. It is 1,2,.... Bedtools will generate conflict if motif file will be having chr1, chr2 ...

**Comment by jjp55** [comment]
My motif file now looks like:
1 	48422	48433	+	8.606111	GTGACATCATCA
1 	55474	55485	-	8.203381	GGGTGGCGTCAT
1 	68644	68655	+	8.327702	ATCACGTCACCA
1 	82144	82155	-	10.331825	TAGTGACGTCAT
1 	95956	95967	+	8.379542	CTGACGTCAGAT

However, I am still getting the same error

**Comment by snizam001** [comment]
Fetch package again (git clone https://github.com/snizam001/cutfrequency.git) and paste the error.

**Comment by jjp55** [comment]
I fetched the package again.

The error I received is:
[1] "==== file preparation: bamfile 3"
[bam_sort_core] merging from 0 files and 20 in-memory blocks...
[1] "==== file preparation: bamfile 4"
[bam_sort_core] merging from 0 files and 20 in-memory blocks...
Warning message:
In fread(paste(bam1, ".input", sep = "")) :
  File 'IP-8hr.input' has size 0. Returning a NULL data.table.
Error in `[.data.frame`(d, , 4) : undefined columns selected
Calls: [ -> [.data.frame -> [ -> [.data.frame
Execution halted


All of the bed3 files contain information.

**Comment by snizam001** [comment]
No problem, check if this command is working:

windowBed -a motifFile -b IP-8HR.bed3 -w 1000 > outfile.input

And paste the head outfile.input

We will solve this.

**Comment by jjp55** [comment]
That seems to be where the problem is. When I run that command I receive an empty file.

**Comment by jjp55** [comment]
The heads if the bed3 is:
1	11	144	NB501800:688:HVMYWBGXJ:2:22310:9078:3546	42	.

And the head of the motif file is:
1 dna_sm:chromosome chromosome:TAIR10:1:1:30427671:1 REF	48422	48433	+	8.606111	GTGACATCATCA

**Comment by snizam001** [comment]
Man, your motif file is still incorrect.

If does not look like this (chromosome start end strand score sequence):
1 48422 48433 + 8.606111 GTGACATCATCA
1 55474 55485 - 8.203381 GGGTGGCGTCAT
1 68644 68655 + 8.327702 ATCACGTCACCA
1 82144 82155 - 10.331825 TAGTGACGTCAT
1 95956 95967 + 8.379542 CTGACGTCAGAT

Instead of this it is (chromosome xyz xyz xyz start end strand score sequence)
1 dna_sm:chromosome chromosome:TAIR10:1:1:30427671:1 REF 48422 48433 + 8.606111 GTGACATCATCA

Correct the motif file and run windowbed command again (windowBed -a motifFile -b IP-8HR.bed3 -w 1000 > outfile.input)

**Comment by jjp55** [comment]
Sorry I posted the head of the wrong motif file. 
The head is:
1 	48422	48433	+	8.606111	GTGACATCATCA
(tab separated)

When running the command:
windowBed -a motif-position.txt -b IP-8hr.bed3 -w 1000 > outfile.input

I still receive an empty outfile.input.

**Comment by snizam001** [comment]
One small doubt, did you generate the motif file for your own organism?

**Comment by jjp55** [comment]
For the motif file, I saved the generate a new pwa file for my transcription factor from HOMER and then did the scanMotifGenomeWide.pl command and saved that resulting file as my motif file.

**Comment by snizam001** [comment]
And you used hg38 in scanmotif command ?

**Comment by jjp55** [comment]
No, I used tair10. My samples are Arabidopsis.

**Comment by snizam001** [comment]
It seems that there is no overlap between the reads of your bamfile at the location of motifs. It is strange.

I can offer you help on anydesk/TeamViewer only.

**Comment by jjp55** [comment]
Thank you for your help (and thank you more for your time). I will try a few more of my files and see if this is a problem they are all having.

**Comment by jjp55** [comment]
Thank you for your help. The problem was the motif file. After reading it into R and exporting it again as a txt, the problem was solve

**Comment by snizam001** [comment]
Perfect, I am closing this issue now.
