### ISSUE TITLE
Error at Ouput

### ISSUE THREAD

**Issue by powersj15** [snizam001/cutfrequency#7]
Hello, I am using your package and got this error.

[1] "=== output of counts in table "
Error in `[.default`(mytable_ctrl, rowSums(mytable_expr) > 1, ) : 
  (subscript) logical subscript too long
Calls: write.table -> is.data.frame -> [ -> [.table -> NextMethod
Execution halted

The code I am running is:

Rscript run.R -a IP -b input -c IP_spikein -d input_spikein -m motif.txt -x 3 -s /cutfrequency-master/ -n 20

**Comment by snizam001** [comment]
Try to run first example files of the package. If there is no error then problem is in your input files.
